### ISSUE TITLE
Ask for help about codes.

### ISSUE THREAD

**Issue by jsjs2009** [nijianmo/fit-rec#1]
Thanks for sharing your source codes. But I didn't find the codes  of the PERSONALIZED RECOMMENDATION (Section 5 in your paper). If it ’s convenient,  could you also share this section.
I will be very grateful

**Comment by nijianmo** [comment]
Hi, we use an approximate Dynamic Time Warping (DTW) algorithm to measure the similarity between two workout profile sequences. Basically our evaluation consists of the following steps:
1. Apply the model on the gold workout route, predict the heart rate profile H
2. Use DTW to calculate the similarity S between predicted heart rate profile H and gold profile H'
3. Apply the model on 100 negative workout routes, predict the heart rate profile H1,...,H100
4. Use DTW to calculate the similarity S1,...,S100 between predicted heart rate profile H1,...,H100 and gold profile H'
5. Rank S0 along with S1,...,S100

The evaluation function is similar to the following:
```
def eval_one_rating(idx):

    gold = _samples[idx][0]
    pos_pred = _samples[idx][1]
    neg_predictions = _samples[idx][2]

    ranks = [(i, fastdtw(gold, neg_pred, dist=euclidean)[0]) for i, neg_pred in enumerate(neg_predictions)]
    distance = fastdtw(gold pos_pred, dist=euclidean)
    ranks.append((-1, distance))

    # sort on distance
    ranks2 = sorted(ranks, key=lambda x: x[1])
    return ranks2.index((-1, distance))
```

**Comment by jsjs2009** [comment]
Thanks for your reply！
